Attribute VB_Name = "NxGeneratedLaunchRegistry"
Option Explicit
' GENERATED FILE - edit contracts/feature-contract.json
Public Sub NxConfigureGeneratedLaunch(ByVal definition As CNxFeatureDefinition, ByVal featureId As String)
    If definition Is Nothing Then NxRaiseContractError "Feature definition is required"
    If Len(featureId) = 0 Then NxRaiseContractError "Feature ID is required"
    Select Case featureId
        Case "NX-AI-SUMMARY"
            definition.ConfigureLaunch "workbench", "NX-DLG-AI-WORKBENCH", "FNxAi", "summary", vbNullString, "NX-ASSET-DATA-AI-WORKBENCH-V34", "adapt"
        Case "NX-AI-CLEAN"
            definition.ConfigureLaunch "workbench", "NX-DLG-AI-WORKBENCH", "FNxAi", "clean", vbNullString, "NX-ASSET-DATA-AI-WORKBENCH-V34", "adapt"
        Case "NX-AI-FORMULA"
            definition.ConfigureLaunch "workbench", "NX-DLG-AI-WORKBENCH", "FNxAi", "formula", vbNullString, "NX-ASSET-DATA-AI-WORKBENCH-V34", "adapt"
        Case "NX-AI-WRITE"
            definition.ConfigureLaunch "workbench", "NX-DLG-AI-WORKBENCH", "FNxAi", "write", vbNullString, "NX-ASSET-DATA-AI-WORKBENCH-V34", "adapt"
        Case "NX-AI-IMAGE"
            definition.ConfigureLaunch "workbench", "NX-DLG-AI-WORKBENCH", "FNxAi", "image", vbNullString, "NX-ASSET-DATA-AI-WORKBENCH-V34", "adapt"
        Case "NX-TPL-REGISTER-SHEET"
            definition.ConfigureLaunch "dialog", "NX-DLG-TPL-REGISTER", "FNxTemplateRegister", "sheet", vbNullString, vbNullString, "direct"
        Case "NX-TPL-LIST"
            definition.ConfigureLaunch "dialog", "NX-DLG-TPL-MANAGER", "FNxTemplateManager", "list", vbNullString, vbNullString, "direct"
        Case "NX-TPL-LOAD"
            definition.ConfigureLaunch "dialog", "NX-DLG-TPL-MANAGER", "FNxTemplateManager", "load", vbNullString, vbNullString, "direct"
        Case "NX-TPL-RENAME"
            definition.ConfigureLaunch "dialog", "NX-DLG-TPL-MANAGER", "FNxTemplateManager", "rename", vbNullString, vbNullString, "direct"
        Case "NX-TPL-DELETE"
            definition.ConfigureLaunch "dialog", "NX-DLG-TPL-MANAGER", "FNxTemplateManager", "delete", vbNullString, vbNullString, "direct"
        Case "NX-DATA-NORMALIZE"
            definition.ConfigureLaunch "dialog", "NX-DLG-DATA-NORMALIZE", "FNxDataNormalize", "normalize", vbNullString, "NX-ASSET-DATA-AI-WORKBENCH-V34", "adapt"
        Case "NX-DATA-UNIQUE-COUNT"
            definition.ConfigureLaunch "dialog", "NX-DLG-DATA-ANALYZE", "FNxDataAnalyze", "unique-count", vbNullString, vbNullString, "direct"
        Case "NX-DATA-DUPLICATE-LIST"
            definition.ConfigureLaunch "dialog", "NX-DLG-DATA-ANALYZE", "FNxDataAnalyze", "duplicate-list", vbNullString, vbNullString, "direct"
        Case "NX-DATA-AGE"
            definition.ConfigureLaunch "dialog", "NX-DLG-DATA-SPECIAL", "FNxAgeCalculator", "age", vbNullString, "NX-ASSET-V34-SPECIAL-CATALOG", "clean-room"
        Case "NX-DATA-KOREAN-MONEY"
            definition.ConfigureLaunch "dialog", "NX-DLG-DATA-SPECIAL", "FNxDataSpecial", "korean-money", vbNullString, "NX-ASSET-V34-SPECIAL-CATALOG", "clean-room"
        Case "NX-DATA-PRIVACY-MASK"
            definition.ConfigureLaunch "dialog", "NX-DLG-DATA-SPECIAL", "FNxDataSpecial", "privacy-mask", vbNullString, "NX-ASSET-V34-SPECIAL-CATALOG", "clean-room"
        Case "NX-DATA-PRIVACY-SCAN"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, "NX-ASSET-V34-SPECIAL-CATALOG", "clean-room"
        Case "NX-DATA-FOCUS-CELL"
            definition.ConfigureLaunch "hybrid", "NX-DLG-FOCUS-SETTINGS", "FNxFocusSettings", "focus-settings", "NxFocusIsEnabled", "NX-ASSET-FOCUS-LIFECYCLE-V34", "adapt"
        Case "NX-DATA-COPY-VISIBLE"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, "NX-ASSET-CLIPBOARD-V34", "adapt"
        Case "NX-DATA-PASTE-VISIBLE-VALUES"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, "NX-ASSET-CLIPBOARD-V34", "adapt"
        Case "NX-HANGUL-TABLE-SEND"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, "NX-ASSET-HANGUL-TABLE-SEND-V34", "adapt"
        Case "NX-HANGUL-PICTURE-SEND"
            definition.ConfigureLaunch "dialog", "NX-DLG-HANGUL-PICTURES", "FNxHangulPictures", "hangul-pictures", vbNullString, vbNullString, "clean-room"
        Case "NX-DRAW-TITLE-TABLE"
            definition.ConfigureLaunch "dialog", "NX-DLG-DRAW-TABLE", "FNxDrawTable", "title-table", vbNullString, vbNullString, "direct"
        Case "NX-DRAW-BUSINESS-TABLE"
            definition.ConfigureLaunch "dialog", "NX-DLG-DRAW-TABLE", "FNxDrawTable", "business-table", vbNullString, vbNullString, "direct"
        Case "NX-DRAW-ROLE-STYLE"
            definition.ConfigureLaunch "dialog", "NX-DLG-DRAW-ROLE-STYLE", "FNxRoleStyle", "role-style", vbNullString, "NX-ASSET-ROLE-STYLE-V34", "adapt"
        Case "NX-DRAW-CLEAR-INNER"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, vbNullString, "direct"
        Case "NX-DRAW-FIT-PICTURE"
            definition.ConfigureLaunch "dialog", "NX-DLG-DRAW-INSERT-PICTURE", "FNxPictureInsert", "picture-fit", vbNullString, vbNullString, "direct"
        Case "NX-DRAW-INSERT-PICTURE"
            definition.ConfigureLaunch "dialog", "NX-DLG-DRAW-INSERT-PICTURE", "FNxPictureInsert", "picture-insert", vbNullString, vbNullString, "adapt"
        Case "NX-FILE-FOLDER-CREATE"
            definition.ConfigureLaunch "dialog", "NX-DLG-FILE-FOLDER-CREATE", "FNxFolderCreate", "folder-create", vbNullString, vbNullString, "adapt"
        Case "NX-FILE-CONSOLIDATE"
            definition.ConfigureLaunch "dialog", "NX-DLG-FILE-CONSOLIDATE", "FNxFileConsolidate", "consolidate", vbNullString, vbNullString, "direct"
        Case "NX-FILE-MANNER-SAVE"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, vbNullString, "direct"
        Case "NX-FILE-RANGE-PNG"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, vbNullString, "direct"
        Case "NX-FILE-CHART-PNG"
            definition.ConfigureLaunch "dialog", "NX-DLG-FILE-OUTPUT", "FNxFileOutput", "chart-png", vbNullString, vbNullString, "direct"
        Case "NX-FILE-SHEET-COPY-SAVE"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, vbNullString, "clean-room"
        Case "NX-FILE-RANGE-COPY-SAVE"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, vbNullString, "clean-room"
        Case "NX-FILE-WORKBOOK-COMPARE"
            definition.ConfigureLaunch "dialog", "NX-DLG-DATA-COMPARE", "FNxDataCompare", "range-compare", vbNullString, vbNullString, "clean-room"
        Case "NX-FILE-BATCH-RENAME"
            definition.ConfigureLaunch "dialog", "NX-DLG-FILE-BATCH-RENAME", "FNxBatchRename", "file-rename", vbNullString, "NX-ASSET-V34-BATCH-RENAME", "adapt"
        Case "NX-FILE-SHEET-BATCH-RENAME"
            definition.ConfigureLaunch "dialog", "NX-DLG-FILE-BATCH-RENAME", "FNxBatchRename", "sheet-rename", vbNullString, vbNullString, "clean-room"
        Case "NX-FILE-PDF-CURRENT-SHEET"
            definition.ConfigureLaunch "dialog", "NX-DLG-FILE-PDF", "FNxPdf", "current-sheet", vbNullString, vbNullString, "clean-room"
        Case "NX-FILE-PDF-EACH-SHEET"
            definition.ConfigureLaunch "dialog", "NX-DLG-FILE-PDF", "FNxPdf", "each-sheet", vbNullString, vbNullString, "clean-room"
        Case "NX-FILE-PDF-SELECTED-COMBINED"
            definition.ConfigureLaunch "dialog", "NX-DLG-FILE-PDF", "FNxPdf", "selected-combined", vbNullString, vbNullString, "clean-room"
        Case "NX-FILE-PDF-ALL-COMBINED"
            definition.ConfigureLaunch "dialog", "NX-DLG-FILE-PDF", "FNxPdf", "all-combined", vbNullString, vbNullString, "clean-room"
        Case "NX-FILE-PDF-SETTINGS"
            definition.ConfigureLaunch "dialog", "NX-DLG-FILE-PDF", "FNxPdf", "settings", vbNullString, vbNullString, "clean-room"
        Case "NX-UTIL-CALCULATOR"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, vbNullString, "clean-room"
        Case "NX-UTIL-SYMBOLS"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, vbNullString, "clean-room"
        Case "NX-UTIL-NAVIGATOR"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, vbNullString, "clean-room"
        Case "NX-UTIL-DOCUMENT-NAVIGATOR"
            definition.ConfigureLaunch "direct", vbNullString, vbNullString, vbNullString, vbNullString, vbNullString, "clean-room"
        Case "NX-FILE-SHEET-COMPARE"
            definition.ConfigureLaunch "dialog", "NX-DLG-DATA-COMPARE", "FNxDataCompare", "sheet-compare", vbNullString, vbNullString, "clean-room"
        Case "NX-FILE-FILE-COMPARE"
            definition.ConfigureLaunch "dialog", "NX-DLG-WORKBOOK-COMPARE", "FNxWorkbookCompare", "file-compare", vbNullString, vbNullString, "clean-room"
        Case Else: NxRaiseContractError "Unknown generated launch feature"
    End Select
End Sub

Public Function NxGeneratedFeatureLabel(ByVal featureId As String) As String
    Select Case featureId
        Case "NX-AI-SUMMARY"
            NxGeneratedFeatureLabel = "요약·분석"
        Case "NX-AI-CLEAN"
            NxGeneratedFeatureLabel = "데이터 정리"
        Case "NX-AI-FORMULA"
            NxGeneratedFeatureLabel = "수식 도우미"
        Case "NX-AI-WRITE"
            NxGeneratedFeatureLabel = "AI 문서 작성"
        Case "NX-AI-IMAGE"
            NxGeneratedFeatureLabel = "AI 이미지 활용"
        Case "NX-TPL-REGISTER-SHEET"
            NxGeneratedFeatureLabel = "현재 시트 템플릿 등록"
        Case "NX-TPL-LIST"
            NxGeneratedFeatureLabel = "템플릿"
        Case "NX-TPL-LOAD"
            NxGeneratedFeatureLabel = "템플릿 사용"
        Case "NX-TPL-RENAME"
            NxGeneratedFeatureLabel = "템플릿 이름 바꾸기"
        Case "NX-TPL-DELETE"
            NxGeneratedFeatureLabel = "템플릿 제거"
        Case "NX-DATA-NORMALIZE"
            NxGeneratedFeatureLabel = "데이터 정규화"
        Case "NX-DATA-UNIQUE-COUNT"
            NxGeneratedFeatureLabel = "고유값 개수"
        Case "NX-DATA-DUPLICATE-LIST"
            NxGeneratedFeatureLabel = "중복 목록"
        Case "NX-DATA-AGE"
            NxGeneratedFeatureLabel = "만나이 계산"
        Case "NX-DATA-KOREAN-MONEY"
            NxGeneratedFeatureLabel = "한글 금액 변환"
        Case "NX-DATA-PRIVACY-MASK"
            NxGeneratedFeatureLabel = "개인정보 마스킹"
        Case "NX-DATA-PRIVACY-SCAN"
            NxGeneratedFeatureLabel = "개인정보 의심 항목 점검"
        Case "NX-DATA-FOCUS-CELL"
            NxGeneratedFeatureLabel = "포커스셀"
        Case "NX-DATA-COPY-VISIBLE"
            NxGeneratedFeatureLabel = "보이는 셀만 복사"
        Case "NX-DATA-PASTE-VISIBLE-VALUES"
            NxGeneratedFeatureLabel = "보이는 셀에 값 붙여넣기"
        Case "NX-HANGUL-TABLE-SEND"
            NxGeneratedFeatureLabel = "아래한글 표 전송"
        Case "NX-HANGUL-PICTURE-SEND"
            NxGeneratedFeatureLabel = "아래한글 그림 전송"
        Case "NX-DRAW-TITLE-TABLE"
            NxGeneratedFeatureLabel = "타이틀표 그리기"
        Case "NX-DRAW-BUSINESS-TABLE"
            NxGeneratedFeatureLabel = "표 그리기"
        Case "NX-DRAW-ROLE-STYLE"
            NxGeneratedFeatureLabel = "내엑셀 스타일"
        Case "NX-DRAW-CLEAR-INNER"
            NxGeneratedFeatureLabel = "내부선 제거"
        Case "NX-DRAW-FIT-PICTURE"
            NxGeneratedFeatureLabel = "그림 셀 맞춤"
        Case "NX-DRAW-INSERT-PICTURE"
            NxGeneratedFeatureLabel = "그림 삽입"
        Case "NX-FILE-FOLDER-CREATE"
            NxGeneratedFeatureLabel = "폴더 일괄 생성"
        Case "NX-FILE-CONSOLIDATE"
            NxGeneratedFeatureLabel = "파일 통합"
        Case "NX-FILE-MANNER-SAVE"
            NxGeneratedFeatureLabel = "매너 저장"
        Case "NX-FILE-RANGE-PNG"
            NxGeneratedFeatureLabel = "선택 범위 그림 저장"
        Case "NX-FILE-CHART-PNG"
            NxGeneratedFeatureLabel = "차트 그림 저장"
        Case "NX-FILE-SHEET-COPY-SAVE"
            NxGeneratedFeatureLabel = "현재 시트 사본 저장"
        Case "NX-FILE-RANGE-COPY-SAVE"
            NxGeneratedFeatureLabel = "선택 범위 사본 저장"
        Case "NX-FILE-WORKBOOK-COMPARE"
            NxGeneratedFeatureLabel = "범위 비교"
        Case "NX-FILE-BATCH-RENAME"
            NxGeneratedFeatureLabel = "파일 이름 일괄 변경"
        Case "NX-FILE-SHEET-BATCH-RENAME"
            NxGeneratedFeatureLabel = "시트 이름 일괄 변경"
        Case "NX-FILE-PDF-CURRENT-SHEET"
            NxGeneratedFeatureLabel = "현재 시트 PDF 저장"
        Case "NX-FILE-PDF-EACH-SHEET"
            NxGeneratedFeatureLabel = "시트별 PDF 저장"
        Case "NX-FILE-PDF-SELECTED-COMBINED"
            NxGeneratedFeatureLabel = "선택 시트 PDF 합치기"
        Case "NX-FILE-PDF-ALL-COMBINED"
            NxGeneratedFeatureLabel = "문서 PDF 저장"
        Case "NX-FILE-PDF-SETTINGS"
            NxGeneratedFeatureLabel = "PDF 저장 설정"
        Case "NX-UTIL-CALCULATOR"
            NxGeneratedFeatureLabel = "계산기"
        Case "NX-UTIL-SYMBOLS"
            NxGeneratedFeatureLabel = "기호표"
        Case "NX-UTIL-NAVIGATOR"
            NxGeneratedFeatureLabel = "탐색창"
        Case "NX-UTIL-DOCUMENT-NAVIGATOR"
            NxGeneratedFeatureLabel = "문서·시트 탐색"
        Case "NX-FILE-SHEET-COMPARE"
            NxGeneratedFeatureLabel = "시트 비교"
        Case "NX-FILE-FILE-COMPARE"
            NxGeneratedFeatureLabel = "파일 비교"
        Case Else: NxRaiseContractError "Unknown generated feature label"
    End Select
End Function

Public Function NxGeneratedFeatureImageMso(ByVal featureId As String) As String
    Select Case featureId
        Case "NX-AI-SUMMARY"
            NxGeneratedFeatureImageMso = "SmartArtInsert"
        Case "NX-AI-CLEAN"
            NxGeneratedFeatureImageMso = "TextDirectionLeftToRight"
        Case "NX-AI-FORMULA"
            NxGeneratedFeatureImageMso = "TableFormulaDialog"
        Case "NX-AI-WRITE"
            NxGeneratedFeatureImageMso = "SmartArtInsert"
        Case "NX-AI-IMAGE"
            NxGeneratedFeatureImageMso = "ControlImage"
        Case "NX-TPL-REGISTER-SHEET"
            NxGeneratedFeatureImageMso = "FileSaveAs"
        Case "NX-TPL-LIST"
            NxGeneratedFeatureImageMso = "PropertySheet"
        Case "NX-TPL-LOAD"
            NxGeneratedFeatureImageMso = "FileOpen"
        Case "NX-TPL-RENAME"
            NxGeneratedFeatureImageMso = "FileProperties"
        Case "NX-TPL-DELETE"
            NxGeneratedFeatureImageMso = "DataFormDeleteRecord"
        Case "NX-DATA-NORMALIZE"
            NxGeneratedFeatureImageMso = "TextDirectionLeftToRight"
        Case "NX-DATA-UNIQUE-COUNT"
            NxGeneratedFeatureImageMso = "NumberingGallery"
        Case "NX-DATA-DUPLICATE-LIST"
            NxGeneratedFeatureImageMso = "TableInsert"
        Case "NX-DATA-AGE"
            NxGeneratedFeatureImageMso = "DateAndTimeInsert"
        Case "NX-DATA-KOREAN-MONEY"
            NxGeneratedFeatureImageMso = "AccountingFormat"
        Case "NX-DATA-PRIVACY-MASK"
            NxGeneratedFeatureImageMso = "ProtectDocument"
        Case "NX-DATA-PRIVACY-SCAN"
            NxGeneratedFeatureImageMso = "FileCheckOut"
        Case "NX-DATA-FOCUS-CELL"
            NxGeneratedFeatureImageMso = "TableStyleBandedColumns"
        Case "NX-DATA-COPY-VISIBLE"
            NxGeneratedFeatureImageMso = "Copy"
        Case "NX-DATA-PASTE-VISIBLE-VALUES"
            NxGeneratedFeatureImageMso = "Paste"
        Case "NX-HANGUL-TABLE-SEND"
            NxGeneratedFeatureImageMso = "FileSendAsAttachment"
        Case "NX-HANGUL-PICTURE-SEND"
            NxGeneratedFeatureImageMso = "PictureInsertFromFile"
        Case "NX-DRAW-TITLE-TABLE"
            NxGeneratedFeatureImageMso = "BorderOutside"
        Case "NX-DRAW-BUSINESS-TABLE"
            NxGeneratedFeatureImageMso = "TableAutoFormat"
        Case "NX-DRAW-ROLE-STYLE"
            NxGeneratedFeatureImageMso = "WordArtInsertGallery"
        Case "NX-DRAW-CLEAR-INNER"
            NxGeneratedFeatureImageMso = "BorderOutside"
        Case "NX-DRAW-FIT-PICTURE"
            NxGeneratedFeatureImageMso = "DrawingCanvasFit"
        Case "NX-DRAW-INSERT-PICTURE"
            NxGeneratedFeatureImageMso = "PictureInsertFromFile"
        Case "NX-FILE-FOLDER-CREATE"
            NxGeneratedFeatureImageMso = "Folder"
        Case "NX-FILE-CONSOLIDATE"
            NxGeneratedFeatureImageMso = "FileOpen"
        Case "NX-FILE-MANNER-SAVE"
            NxGeneratedFeatureImageMso = "FileSave"
        Case "NX-FILE-RANGE-PNG"
            NxGeneratedFeatureImageMso = "FileSaveAs"
        Case "NX-FILE-CHART-PNG"
            NxGeneratedFeatureImageMso = "FileSaveAs"
        Case "NX-FILE-SHEET-COPY-SAVE"
            NxGeneratedFeatureImageMso = "FileSaveAs"
        Case "NX-FILE-RANGE-COPY-SAVE"
            NxGeneratedFeatureImageMso = "FileSaveAs"
        Case "NX-FILE-WORKBOOK-COMPARE"
            NxGeneratedFeatureImageMso = "WindowsArrangeAll"
        Case "NX-FILE-BATCH-RENAME"
            NxGeneratedFeatureImageMso = "FileProperties"
        Case "NX-FILE-SHEET-BATCH-RENAME"
            NxGeneratedFeatureImageMso = "NameDefine"
        Case "NX-FILE-PDF-CURRENT-SHEET"
            NxGeneratedFeatureImageMso = "FileSaveAsPdfOrXps"
        Case "NX-FILE-PDF-EACH-SHEET"
            NxGeneratedFeatureImageMso = "FileSaveAsPdfOrXps"
        Case "NX-FILE-PDF-SELECTED-COMBINED"
            NxGeneratedFeatureImageMso = "FileSaveAsPdfOrXps"
        Case "NX-FILE-PDF-ALL-COMBINED"
            NxGeneratedFeatureImageMso = "FileSaveAsPdfOrXps"
        Case "NX-FILE-PDF-SETTINGS"
            NxGeneratedFeatureImageMso = "FileProperties"
        Case "NX-UTIL-CALCULATOR"
            NxGeneratedFeatureImageMso = "CalculateNow"
        Case "NX-UTIL-SYMBOLS"
            NxGeneratedFeatureImageMso = "SymbolInsert"
        Case "NX-UTIL-NAVIGATOR"
            NxGeneratedFeatureImageMso = "ControlProperties"
        Case "NX-UTIL-DOCUMENT-NAVIGATOR"
            NxGeneratedFeatureImageMso = "FindDialog"
        Case "NX-FILE-SHEET-COMPARE"
            NxGeneratedFeatureImageMso = "WindowsArrangeAll"
        Case "NX-FILE-FILE-COMPARE"
            NxGeneratedFeatureImageMso = "FileOpen"
        Case Else: NxRaiseContractError "Unknown generated feature image"
    End Select
End Function
