Attribute VB_Name = "NxGeneratedCommandRegistry"
Option Explicit

Public Sub NxRegisterGeneratedCommands(ByVal registry As CNxCommandRegistry)
    ' Each generated row carries the sealed shortcutEligible decision.
    registry.Add "NX-CMD-STYLE-FONT-SIZE-9", "글자 크기 9", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "NX_STYLE_FONT_SIZE_9", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-FONT-SIZE-10", "글자 크기 10", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "NX_STYLE_FONT_SIZE_10", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-FONT-SIZE-12", "글자 크기 12", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "NX_STYLE_FONT_SIZE_12", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-FONT-SIZE-15", "글자 크기 15", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "NX_STYLE_FONT_SIZE_15", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-FONT-COLOR-BLACK", "글자색 검정", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "NX_STYLE_FONT_COLOR_BLACK", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-FONT-COLOR-RED", "글자색 빨강", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "NX_STYLE_FONT_COLOR_RED", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-FONT-COLOR-BLUE", "글자색 파랑", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "NX_STYLE_FONT_COLOR_BLUE", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-FONT-COLOR-GREEN", "글자색 초록", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "NX_STYLE_FONT_COLOR_GREEN", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-FILL-GRAY", "채우기 회색", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "NX_STYLE_FILL_GRAY", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-FILL-LIGHT-RED", "채우기 연한 빨강", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "NX_STYLE_FILL_LIGHT_RED", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-FILL-LIGHT-YELLOW", "채우기 연한 노랑", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "NX_STYLE_FILL_LIGHT_YELLOW", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-FILL-LIGHT-GREEN", "채우기 연한 초록", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "NX_STYLE_FILL_LIGHT_GREEN", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-CLIPBOARD-RB-CLIPBOARD-COPY-BYFORMULA", "첫 셀 수식 복사", "NX-CAT-DATA", "NX-CMD-GRP-CLIPBOARD", "NxCmdClipboard", "RB_CLIPBOARD_COPY_BYFORMULA", False, True, "none"
    registry.Add "NX-CMD-CLIPBOARD-RB-CLIPBOARD-COPY-BYREFERENCE", "첫 셀 주소 복사", "NX-CAT-DATA", "NX-CMD-GRP-CLIPBOARD", "NxCmdClipboard", "RB_CLIPBOARD_COPY_BYREFERENCE", False, True, "none"
    registry.Add "NX-CMD-CLIPBOARD-RB-CLIPBOARD-COPY-BYTEXT", "보이는 값 복사", "NX-CAT-DATA", "NX-CMD-GRP-CLIPBOARD", "NxCmdClipboard", "RB_CLIPBOARD_COPY_BYTEXT", False, True, "none"
    registry.Add "NX-CMD-CLIPBOARD-RB-LHECLIPBOARD-COPYVISIBLE", "보이는 셀만 복사", "NX-CAT-DATA", "NX-CMD-GRP-CLIPBOARD", "NxCmdClipboard", "RB_LHECLIPBOARD_COPYVISIBLE", False, True, "none"
    registry.Add "NX-CMD-CLIPBOARD-RB-LHECLIPBOARD-PASTEVISIBLEVALUES", "보이는 셀에 값 붙여넣기", "NX-CAT-DATA", "NX-CMD-GRP-CLIPBOARD", "NxCmdClipboard", "RB_LHECLIPBOARD_PASTEVISIBLEVALUES", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-CLIPBOARD-RB-LHECLIPBOARD-PASTEVISIBLEFORMULAS", "보이는 셀에 수식 붙여넣기", "NX-CAT-DATA", "NX-CMD-GRP-CLIPBOARD", "NxCmdClipboard", "RB_LHECLIPBOARD_PASTEVISIBLEFORMULAS", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-CLIPBOARD-RB-LHECLIPBOARD-PASTEVISIBLEFORMATS", "보이는 셀에 서식 붙여넣기", "NX-CAT-DATA", "NX-CMD-GRP-CLIPBOARD", "NxCmdClipboard", "RB_LHECLIPBOARD_PASTEVISIBLEFORMATS", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-PRINT-RB-PRINT-SETUP-QUICK", "선택 범위 인쇄 미리보기", "NX-CAT-FILE", "NX-CMD-GRP-PRINT", "NxCmdPrint", "RB_PRINT_SETUP_QUICK", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-PRINT-RB-PRINT-SETUP-QUICK-PORTRAIT", "세로 방향 · 너비 1쪽", "NX-CAT-FILE", "NX-CMD-GRP-PRINT", "NxCmdPrint", "RB_PRINT_SETUP_QUICK_PORTRAIT", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-PRINT-RB-PRINT-SETUP-QUICK-LANDSCAPE", "가로 방향 · 너비 1쪽", "NX-CAT-FILE", "NX-CMD-GRP-PRINT", "NxCmdPrint", "RB_PRINT_SETUP_QUICK_LANDSCAPE", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-PRINT-RB-PRINT-SETUP-QUICK-PORTRAIT-1BY1", "세로 방향 · 한 장에 맞춤", "NX-CAT-FILE", "NX-CMD-GRP-PRINT", "NxCmdPrint", "RB_PRINT_SETUP_QUICK_PORTRAIT_1BY1", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-PRINT-RB-PRINT-SETUP-QUICK-LANDSCAPE-1BY1", "가로 방향 · 한 장에 맞춤", "NX-CAT-FILE", "NX-CMD-GRP-PRINT", "NxCmdPrint", "RB_PRINT_SETUP_QUICK_LANDSCAPE_1BY1", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-PRINT-RB-PRINT-SETUP-REPEAT", "선택 행을 인쇄 제목으로", "NX-CAT-FILE", "NX-CMD-GRP-PRINT", "NxCmdPrint", "RB_PRINT_SETUP_REPEAT", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-PRINT-RB-LHEPRINT-ADD1MMSPACER", "인쇄용 1mm 여백 추가", "NX-CAT-FILE", "NX-CMD-GRP-PRINT", "NxCmdPrint", "RB_LHEPRINT_ADD1MMSPACER", True, False, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-RESETWORKBOOKSTYLES", "사용자 스타일 정리", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_RESETWORKBOOKSTYLES", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-OPENOPTIONS", "내엑셀 스타일", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_OPENOPTIONS", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-MONO-TITLE", "흑백 · 제목", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_MONO_TITLE", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-MONO-SUBTITLE", "흑백 · 소제목", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_MONO_SUBTITLE", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-MONO-TABLEHEADER", "흑백 · 표 머리글", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_MONO_TABLEHEADER", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-MONO-TABLEBODY", "흑백 · 표 본문", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_MONO_TABLEBODY", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-MONO-EMPHASISCELL", "흑백 · 강조 셀", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_MONO_EMPHASISCELL", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-MONO-TOTALROW", "흑백 · 합계 행", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_MONO_TOTALROW", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-COLOR-TITLE", "컬러 · 제목", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_COLOR_TITLE", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-COLOR-SUBTITLE", "컬러 · 소제목", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_COLOR_SUBTITLE", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-COLOR-TABLEHEADER", "컬러 · 표 머리글", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_COLOR_TABLEHEADER", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-COLOR-TABLEBODY", "컬러 · 표 본문", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_COLOR_TABLEBODY", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-EDIT-MEMO-ADD-LHEXCELFORMULA", "셀수식 메모 기록", "NX-CAT-DRAW", "NX-CMD-GRP-FORMULA-REFERENCE", "NxCmdStyle", "RB_EDIT_MEMO_ADD_LHEXCELFORMULA", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-COLOR-EMPHASISCELL", "컬러 · 강조 셀", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_COLOR_EMPHASISCELL", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STYLE-RB-LHESTYLE-COLOR-TOTALROW", "컬러 · 합계 행", "NX-CAT-DRAW", "NX-CMD-GRP-STYLE", "NxCmdStyle", "RB_LHESTYLE_COLOR_TOTALROW", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-NUMBER-RB-EDIT-NUMBERFORMAT-NUMBER", "천 단위 구분 · 정수", "NX-CAT-DRAW", "NX-CMD-GRP-NUMBER-FORMAT", "NxCmdNumberFormat", "RB_EDIT_NUMBERFORMAT_NUMBER", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-NUMBER-RB-EDIT-NUMBERFORMAT-PERCENTAGE", "백분율 표시 · 자릿수 선택", "NX-CAT-DRAW", "NX-CMD-GRP-NUMBER-FORMAT", "NxCmdNumberFormat", "RB_EDIT_NUMBERFORMAT_PERCENTAGE", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-NUMBER-RB-EDIT-NUMBERFORMAT-DECIMAL", "숫자 표시 · 소수 자릿수 선택", "NX-CAT-DRAW", "NX-CMD-GRP-NUMBER-FORMAT", "NxCmdNumberFormat", "RB_EDIT_NUMBERFORMAT_DECIMAL", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-SELECTION-RB-APP-OPTION-EDITDIRECTION-CHANGE", "Enter 이동 방향 변경", "NX-CAT-DATA", "NX-CMD-GRP-SELECTION-MOVE", "NxCmdSelection", "RB_APP_OPTION_EDITDIRECTION_CHANGE", False, False, "none"
    registry.Add "NX-CMD-SELECTION-RB-SELECTION-CELL-USEDRANGE", "내용이 있는 셀 모두 선택", "NX-CAT-DATA", "NX-CMD-GRP-SELECTION-MOVE", "NxCmdSelection", "RB_SELECTION_CELL_USEDRANGE", False, False, "none"
    registry.Add "NX-CMD-SELECTION-RB-SELECTION-CELL-TEXT-SPECIFIC", "특정 문자가 포함된 모든셀 선택", "NX-CAT-DATA", "NX-CMD-GRP-SELECTION-MOVE", "NxCmdSelection", "RB_SELECTION_CELL_TEXT_SPECIFIC", False, False, "none"
    registry.Add "NX-CMD-SELECTION-RB-SELECTION-CELL-MOVE-LEFT", "여러셀 선택시 선택범위 ←이동", "NX-CAT-DATA", "NX-CMD-GRP-SELECTION-MOVE", "NxCmdSelection", "RB_SELECTION_CELL_MOVE_LEFT", False, False, "none"
    registry.Add "NX-CMD-SELECTION-RB-SELECTION-CELL-MOVE-RIGHT", "여러셀 선택시 선택범위 →이동", "NX-CAT-DATA", "NX-CMD-GRP-SELECTION-MOVE", "NxCmdSelection", "RB_SELECTION_CELL_MOVE_RIGHT", False, False, "none"
    registry.Add "NX-CMD-SELECTION-RB-SELECTION-CELL-MOVE-DOWN", "여러셀 선택시 선택범위 ↓이동", "NX-CAT-DATA", "NX-CMD-GRP-SELECTION-MOVE", "NxCmdSelection", "RB_SELECTION_CELL_MOVE_DOWN", False, False, "none"
    registry.Add "NX-CMD-SELECTION-RB-SELECTION-CELL-MOVE-UP", "여러셀 선택시 선택범위 ↑이동", "NX-CAT-DATA", "NX-CMD-GRP-SELECTION-MOVE", "NxCmdSelection", "RB_SELECTION_CELL_MOVE_UP", False, False, "none"
    registry.Add "NX-CMD-SELECTION-RB-SELECTION-CELL-EXPAND-COL", "(떨어진)셀들의 전체 열 선택", "NX-CAT-DATA", "NX-CMD-GRP-SELECTION-MOVE", "NxCmdSelection", "RB_SELECTION_CELL_EXPAND_COL", False, False, "none"
    registry.Add "NX-CMD-SELECTION-RB-SELECTION-CELL-EXPAND-ROW", "(떨어진)셀들의 전체 행 선택", "NX-CAT-DATA", "NX-CMD-GRP-SELECTION-MOVE", "NxCmdSelection", "RB_SELECTION_CELL_EXPAND_ROW", False, False, "none"
    registry.Add "NX-CMD-SIZE-RB-EDIT-CELL-RESIZE", "셀·글자·도형 크기 조정", "NX-CAT-DATA", "NX-CMD-GRP-ROW-COLUMN", "NxCmdRowsColumns", "RB_EDIT_CELL_RESIZE", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-ALIGN-RB-EDIT-ALIGN-CENTER-OVERCELLS", "모형병합 실행/취소", "NX-CAT-DRAW", "NX-CMD-GRP-ALIGNMENT-MERGE", "NxCmdAlignment", "RB_EDIT_ALIGN_CENTER_OVERCELLS", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-STRUCTURE-RB-EDIT-CELL-MAKEGROUP-HIDDEN-ROWCOLUMN", "선택 행·열 그룹 만들기", "NX-CAT-DATA", "NX-CMD-GRP-INSERT-DELETE-HIDE", "NxCmdInsertDelete", "RB_EDIT_CELL_MAKEGROUP_HIDDEN_ROWCOLUMN", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-FILTER-RB-DATA-SORT-ASCENDING", "오름차순으로 정렬", "NX-CAT-DATA", "NX-CMD-GRP-FILTER-SORT", "NxCmdFilterSort", "RB_DATA_SORT_ASCENDING", True, False, "command_scoped_guard"
    registry.Add "NX-CMD-FILTER-RB-DATA-SORT-DESCENDING", "내림차순으로 정렬", "NX-CAT-DATA", "NX-CMD-GRP-FILTER-SORT", "NxCmdFilterSort", "RB_DATA_SORT_DESCENDING", True, False, "command_scoped_guard"
    registry.Add "NX-CMD-FILTER-RB-FILTER-AUTOFILTER-CANCEL", "자동필터 > 선택열만 필터 취소", "NX-CAT-DATA", "NX-CMD-GRP-FILTER-SORT", "NxCmdFilterSort", "RB_FILTER_AUTOFILTER_CANCEL", True, False, "command_scoped_guard"
    registry.Add "NX-CMD-FILTER-RB-FILTER-AUTOFILTER-FILTERING", "자동필터 > 선택값으로 필터링", "NX-CAT-DATA", "NX-CMD-GRP-FILTER-SORT", "NxCmdFilterSort", "RB_FILTER_AUTOFILTER_FILTERING", True, False, "command_scoped_guard"
    registry.Add "NX-CMD-FILTER-RB-FILTER-AUTOFILTER-FILTERING-OPTIONAL", "자동필터 > 입력 값으로 필터링", "NX-CAT-DATA", "NX-CMD-GRP-FILTER-SORT", "NxCmdFilterSort", "RB_FILTER_AUTOFILTER_FILTERING_OPTIONAL", True, False, "command_scoped_guard"
    registry.Add "NX-CMD-FILTER-RB-FILTER-AUTOFILTER-SHOWALL", "자동필터 > 모든데이터보기", "NX-CAT-DATA", "NX-CMD-GRP-FILTER-SORT", "NxCmdFilterSort", "RB_FILTER_AUTOFILTER_SHOWALL", True, False, "command_scoped_guard"
    registry.Add "NX-CMD-FILTER-RB-DATA-SHOW-SOURCE", "피벗테이블 원본 데이터 필터링", "NX-CAT-DATA", "NX-CMD-GRP-FILTER-SORT", "NxCmdFilterSort", "RB_DATA_SHOW_SOURCE", True, False, "command_scoped_guard"
    registry.Add "NX-CMD-FORMULA-RB-FORMULA-PRECEDENTS-LIST", "수식 참조표 만들기", "NX-CAT-DATA", "NX-CMD-GRP-FORMULA-REFERENCE", "NxCmdFormula", "RB_FORMULA_PRECEDENTS_LIST", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-SHEET-RB-SHEET-SAVE-TO-FILE", "선택 시트들 파일로 저장", "NX-CAT-FILE", "NX-CMD-GRP-SHEET", "NxCmdSheet", "RB_SHEET_SAVE_TO_FILE", True, False, "command_scoped_guard"
    registry.Add "NX-CMD-SHEET-RB-SHEET-SELECT-END", "마지막 시트로 이동", "NX-CAT-FILE", "NX-CMD-GRP-SHEET", "NxCmdSheet", "RB_SHEET_SELECT_END", False, True, "none"
    registry.Add "NX-CMD-SHEET-RB-SHEET-SELECT-HOME", "첫번째 시트로 이동", "NX-CAT-FILE", "NX-CMD-GRP-SHEET", "NxCmdSheet", "RB_SHEET_SELECT_HOME", False, True, "none"
    registry.Add "NX-CMD-VIEW-RB-WINDOWS-VIEW-FULLSCREEN", "전체 화면 켜기/끄기", "NX-CAT-FILE", "NX-CMD-GRP-VIEW-WINDOW", "NxCmdView", "RB_WINDOWS_VIEW_FULLSCREEN", False, True, "none"
    registry.Add "NX-CMD-VIEW-RB-WINDOWS-VIEW-SCROLL-DOWN", "화면 아래쪽으로 스크롤", "NX-CAT-FILE", "NX-CMD-GRP-VIEW-WINDOW", "NxCmdView", "RB_WINDOWS_VIEW_SCROLL_DOWN", False, False, "none"
    registry.Add "NX-CMD-VIEW-RB-WINDOWS-VIEW-SCROLL-LEFT", "화면 왼쪽으로 스크롤", "NX-CAT-FILE", "NX-CMD-GRP-VIEW-WINDOW", "NxCmdView", "RB_WINDOWS_VIEW_SCROLL_LEFT", False, False, "none"
    registry.Add "NX-CMD-VIEW-RB-WINDOWS-VIEW-SCROLL-RIGHT", "화면 오른쪽으로 스크롤", "NX-CAT-FILE", "NX-CMD-GRP-VIEW-WINDOW", "NxCmdView", "RB_WINDOWS_VIEW_SCROLL_RIGHT", False, False, "none"
    registry.Add "NX-CMD-VIEW-RB-WINDOWS-VIEW-SCROLL-UP", "화면 위쪽으로 스크롤", "NX-CAT-FILE", "NX-CMD-GRP-VIEW-WINDOW", "NxCmdView", "RB_WINDOWS_VIEW_SCROLL_UP", False, False, "none"
    registry.Add "NX-CMD-INFO-RB-APP-NAMEUNHIDE", "숨김 이름 정의 표시", "NX-CAT-FILE", "NX-CMD-GRP-INFO-DIAGNOSTICS", "NxCmdInfo", "RB_APP_NAMEUNHIDE", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-INFO-RB-INFO-MEMO-LIST", "문서 메모 목록 만들기", "NX-CAT-FILE", "NX-CMD-GRP-INFO-DIAGNOSTICS", "NxCmdInfo", "RB_INFO_MEMO_LIST", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-INFO-RB-INFO-SHEET-LIST", "문서 시트 목록 만들기", "NX-CAT-FILE", "NX-CMD-GRP-INFO-DIAGNOSTICS", "NxCmdInfo", "RB_INFO_SHEET_LIST", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-INFO-RB-WORKBOOK-INFOMATION", "내엑셀 버전 정보", "NX-CAT-FILE", "NX-CMD-GRP-INFO-DIAGNOSTICS", "NxCmdInfo", "RB_WORKBOOK_INFOMATION", False, False, "none"
    registry.Add "NX-CMD-INFO-RB-SHOW-WORKSHEET-LIST", "현재 파일의 워크시트 목록창", "NX-CAT-FILE", "NX-CMD-GRP-INFO-DIAGNOSTICS", "NxCmdInfo", "RB_SHOW_WORKSHEET_LIST", True, False, "command_scoped_guard"
    registry.Add "NX-CMD-PIVOT-RB-PIVOTLISTOFWB", "피벗테이블 목록 생성", "NX-CAT-DATA", "NX-CMD-GRP-PIVOT", "NxCmdPivot", "RB_PIVOTLISTOFWB", True, False, "command_scoped_guard"
    registry.Add "NX-CMD-PIVOT-RB-PIVOT-BUILDUP", "피벗테이블 관리창 실행", "NX-CAT-DATA", "NX-CMD-GRP-PIVOT", "NxCmdPivot", "RB_PIVOT_BUILDUP", True, False, "command_scoped_guard"
    registry.Add "NX-CMD-DATA-DATE-CONVERT", "날짜 변환", "NX-CAT-DATA", "NX-CMD-GRP-SELECTION-MOVE", "NxCmdSelection", "NX_DATA_DATE_CONVERT", False, True, "none"
    registry.Add "NX-CMD-NUMBER-EMPHASIS", "숫자 강조(▲▼)", "NX-CAT-DRAW", "NX-CMD-GRP-NUMBER-FORMAT", "NxCmdNumberFormat", "NX_NUMBER_EMPHASIS", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-VIEW-PRESET-1", "화면 프리셋 1", "NX-CAT-FILE", "NX-CMD-GRP-VIEW-WINDOW", "NxCmdView", "NX_VIEW_PRESET_1", False, True, "none"
    registry.Add "NX-CMD-VIEW-PRESET-2", "화면 프리셋 2", "NX-CAT-FILE", "NX-CMD-GRP-VIEW-WINDOW", "NxCmdView", "NX_VIEW_PRESET_2", False, True, "none"
    registry.Add "NX-CMD-VIEW-PRESET-3", "화면 프리셋 3", "NX-CAT-FILE", "NX-CMD-GRP-VIEW-WINDOW", "NxCmdView", "NX_VIEW_PRESET_3", False, True, "none"
    registry.Add "NX-CMD-VIEW-PRESET-4", "화면 프리셋 4", "NX-CAT-FILE", "NX-CMD-GRP-VIEW-WINDOW", "NxCmdView", "NX_VIEW_PRESET_4", False, True, "none"
    registry.Add "NX-CMD-VIEW-PRESET-5", "화면 프리셋 5", "NX-CAT-FILE", "NX-CMD-GRP-VIEW-WINDOW", "NxCmdView", "NX_VIEW_PRESET_5", False, True, "none"
    registry.Add "NX-CMD-VIEW-PRESET-SETTINGS", "화면 프리셋 설정", "NX-CAT-FILE", "NX-CMD-GRP-VIEW-WINDOW", "NxCmdView", "NX_VIEW_PRESET_SETTINGS", False, True, "none"
    registry.Add "NX-CMD-FUNCTION-ROUND", "ROUND 감싸기", "NX-CAT-DATA", "NX-CMD-GRP-FORMULA-REFERENCE", "NxCmdFormula", "NX_FUNCTION_ROUND", True, True, "command_scoped_guard"
    registry.Add "NX-CMD-FUNCTION-IFERROR", "IFERROR 감싸기", "NX-CAT-DATA", "NX-CMD-GRP-FORMULA-REFERENCE", "NxCmdFormula", "NX_FUNCTION_IFERROR", True, True, "command_scoped_guard"
End Sub

Public Function NxGeneratedCommandCount() As Long
    NxGeneratedCommandCount = 89
End Function

Public Function NxRibbonOnlyCommandMetadata(ByVal routeKey As String) As String
    Select Case routeKey
        Case "command:NX-CMD-STYLE-FONT-SIZE-9": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
        Case "command:NX-CMD-STYLE-FONT-SIZE-10": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
        Case "command:NX-CMD-STYLE-FONT-SIZE-12": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
        Case "command:NX-CMD-STYLE-FONT-SIZE-15": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
        Case "command:NX-CMD-STYLE-FONT-COLOR-BLACK": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
        Case "command:NX-CMD-STYLE-FONT-COLOR-RED": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
        Case "command:NX-CMD-STYLE-FONT-COLOR-BLUE": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
        Case "command:NX-CMD-STYLE-FONT-COLOR-GREEN": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
        Case "command:NX-CMD-STYLE-FILL-GRAY": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
        Case "command:NX-CMD-STYLE-FILL-LIGHT-RED": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
        Case "command:NX-CMD-STYLE-FILL-LIGHT-YELLOW": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
        Case "command:NX-CMD-STYLE-FILL-LIGHT-GREEN": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
        Case "command:NX-CMD-NUMBER-RB-EDIT-NUMBERFORMAT-NUMBER": NxRibbonOnlyCommandMetadata = "range_selection|required|direct|document"
    End Select
End Function
