param(
    [Parameter(Mandatory=$true)][string]$ProductXlam,
    [Parameter(Mandatory=$true)][string]$EvidenceRoot,
    [string]$RunId = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$SourceRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$ProductXlam = [IO.Path]::GetFullPath($ProductXlam)
$EvidenceRoot = [IO.Path]::GetFullPath($EvidenceRoot)
if ([string]::IsNullOrWhiteSpace($RunId)) { $RunId = [Guid]::NewGuid().ToString().ToLowerInvariant() }
if (-not (Test-Path -LiteralPath $ProductXlam -PathType Leaf)) { throw 'Product.xlam not found' }
if (Test-Path -LiteralPath $EvidenceRoot) { throw 'Existing R58 safe-open evidence root is rejected' }
if (@(Get-Process EXCEL -ErrorAction SilentlyContinue).Count -ne 0) { throw 'R58 safe-open requires zero pre-existing Excel processes' }
. (Join-Path $SourceRoot 'build/Excel-ProcessLifecycle.ps1')

function Write-Json([string]$Path,[object]$Value) { [IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 20)+"`n"),(New-Object Text.UTF8Encoding($false))) }
function Release-Com([object]$Value) { if ($null -ne $Value -and [Runtime.InteropServices.Marshal]::IsComObject($Value)){try{[void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($Value)}catch{}} }
function Release-ComObject([object]$Value) { Release-Com $Value }
function Get-FreshExcelProcessIds() { $rows=@(Get-Process EXCEL -ErrorAction SilentlyContinue);try{return @($rows|ForEach-Object{[int]$_.Id})}finally{foreach($row in $rows){try{$row.Dispose()}catch{}}} }
function Wait-FreshExcelProcessExit([int]$TimeoutMs=2000) { $watch=[Diagnostics.Stopwatch]::StartNew();do{$ids=@(Get-FreshExcelProcessIds);if($ids.Count -eq 0){return [pscustomobject]@{status='CLEARED';remaining_pids=@()}};Start-Sleep -Milliseconds 100}while($watch.ElapsedMilliseconds -lt $TimeoutMs);return [pscustomobject]@{status='REMAINING';remaining_pids=$ids} }
function Get-ModuleBody([string]$Path) { $text=[IO.File]::ReadAllText($Path,[Text.Encoding]::UTF8).Replace("`r`n","`n").Replace("`r","`n"); return (@($text -split "`n"|Where-Object{$_ -notmatch '^\s*Attribute\s+'}) -join "`r`n") }
function Add-VbaModule([object]$Components,[string]$Path,[string]$Name) { $component=$null;$module=$null;try{$component=$Components.Add(1);$component.Name=$Name;$module=$component.CodeModule;[void]$module.AddFromString((Get-ModuleBody $Path))}finally{Release-Com $module;Release-Com $component} }
function Assert-InstrumentedCopyModule([object]$Book,[string]$Name) { $project=$null;$component=$null;$module=$null;try{$project=$Book.VBProject;$component=$project.VBComponents.Item($Name);$module=$component.CodeModule;if($module.CountOfLines -lt 1){throw ('Instrumented copy test module is empty: '+$Name)}}finally{Release-Com $module;Release-Com $component;Release-Com $project} }
function Invoke-R58SafeOpenCompile([object]$Excel,[object]$Binding,[object]$Components,[string]$CopyPath) {
    $vbe=$null;$bars=$null;$control=$null;$target=$null;$active=$null;$main=$null;$watcher=$null
    $script:Compile=[ordered]@{status='RUNNING';control_id=578;active_project=$null;dialog=$null;failure=$null}
    try {
        $vbe=$Excel.VBE;$bars=$vbe.CommandBars;$control=Find-VbeCompileControl $bars
        if($null -eq $control -or [int]$control.Id -ne 578){throw 'R58 safe-open VBE compile control 578 unavailable'}
        $target=$Components.Item('T_R58SafeOpen');[void]$target.Activate();$active=$vbe.ActiveVBProject
        $activePath=[IO.Path]::GetFullPath([string]$active.FileName);$script:Compile.active_project=$activePath
        if($activePath -ne [IO.Path]::GetFullPath($CopyPath)){throw 'R58 safe-open compile active project identity mismatch'}
        if(-not [bool]$control.Enabled){throw 'R58 safe-open VBE compile control was disabled before compile'}
        $main=$vbe.MainWindow;$watcher=Start-ExactOwnedCompileDialogWatcher -ExcelPid ([int]$Binding.pid) -ExcelHwnd ([Int64]$Binding.hwnd) -VbeHwnd ([Int64]$main.HWnd)
        $executeFailure=$null;try{[void]$control.Execute()}catch{$executeFailure=$_.Exception.Message}
        $completed=Wait-Job -Job $watcher -Timeout 30;if($null -eq $completed){Stop-Job $watcher -ErrorAction SilentlyContinue;throw 'R58 safe-open compile watcher timed out'}
        $watch=@(Receive-Job -Job $watcher -Wait -AutoRemoveJob -ErrorAction Stop|Select-Object -First 1);$watcher=$null
        if(-not [string]::IsNullOrWhiteSpace($executeFailure)){throw ('R58 safe-open VBE compile execution failed: '+$executeFailure)}
        if($watch.Count -ne 1 -or [string]$watch[0].status -ne 'NO_DIALOG'){ $script:Compile.dialog=if($watch.Count -eq 1){[string]$watch[0].dialog_text}else{'watcher returned no result'};throw ('R58 safe-open VBA compile dialog detected: '+$script:Compile.dialog) }
        if([bool]$control.Enabled){throw 'R58 safe-open VBE compile did not reach saved disabled state'}
        $script:Compile.status='PASS'
    } catch {$script:Compile.status='FAIL';$script:Compile.failure=$_.Exception.Message;throw}
    finally {if($null -ne $watcher){try{Stop-Job $watcher -ErrorAction SilentlyContinue;Remove-Job $watcher -Force -ErrorAction SilentlyContinue}catch{}};Release-Com $main;Release-Com $active;Release-Com $target;Release-Com $control;Release-Com $bars;Release-Com $vbe}
}
function Add-ZipEntry([IO.Compression.ZipArchive]$Archive,[string]$Name,[string]$Text){$entry=$Archive.CreateEntry($Name);$writer=$null;try{$writer=New-Object IO.StreamWriter($entry.Open(),[Text.Encoding]::UTF8);$writer.Write($Text)}finally{if($null -ne $writer){$writer.Dispose()}}}
function New-OoxmlFixture([string]$Path,[string]$Mode) {
    $stream=$null;$archive=$null
    try {
        $stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);$archive=New-Object IO.Compression.ZipArchive($stream,[IO.Compression.ZipArchiveMode]::Create,$false)
        $content='<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/></Types>'
        $relationships='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'
        $workbookRelations='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>'
        if($Mode -eq 'dtd'){$content='<!DOCTYPE Types [<!ENTITY x "x">]><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/xml"/></Types>'}
        if($Mode -eq 'content-type'){$content='<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Override PartName="/xl/macrosheets/sheet1.xml" ContentType="application/vnd.ms-excel.macrosheet+xml"/></Types>'}
        if($Mode -eq 'relation'){$workbookRelations='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdX" Type="http://schemas.microsoft.com/office/2006/relationships/xlMacrosheet" Target="macrosheets/sheet1.xml"/></Relationships>'}
        Add-ZipEntry $archive '[Content_Types].xml' $content;Add-ZipEntry $archive '_rels/.rels' $relationships;Add-ZipEntry $archive 'xl/workbook.xml' '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>';Add-ZipEntry $archive 'xl/_rels/workbook.xml.rels' $workbookRelations;Add-ZipEntry $archive 'xl/worksheets/sheet1.xml' '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>'
        if($Mode -eq 'macrosheet'){Add-ZipEntry $archive 'xl/macrosheets/sheet1.xml' '<macrosheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>'}
    } finally {if($null -ne $archive){$archive.Dispose()};if($null -ne $stream){$stream.Dispose()}}
}
function New-XlsmMarkerFixture([object]$Excel,[string]$Path,[string]$MarkerPath) {
    $book=$null;$project=$null;$component=$null;$module=$null;$codeName=$null
    try {$book=$Excel.Workbooks.Add();$project=$book.VBProject;$codeName=[string]$book.CodeName;if([string]::IsNullOrWhiteSpace($codeName)){throw 'Marker fixture workbook CodeName is unavailable'};$component=$project.VBComponents.Item($codeName);if([int]$component.Type -ne 100){throw ('Marker fixture workbook component identity mismatch: expected type=100; actual type='+[string]$component.Type+'; codeName='+$codeName)};$module=$component.CodeModule;$escaped=$MarkerPath.Replace('"','""');[void]$module.AddFromString("Private Sub Workbook_Open()`r`nDim h As Integer`r`nh = FreeFile`r`nOpen `"$escaped`" For Append As #h`r`nPrint #h, `"EXECUTED`"`r`nClose #h`r`nEnd Sub");$book.SaveAs($Path,52);$book.Close($false);$book=$null} finally {if($null -ne $book){try{$book.Close($false)}catch{}};Release-Com $module;Release-Com $component;Release-Com $project;Release-Com $book}
}
function New-NormalXlsxFixture([object]$Excel,[string]$Path) { $book=$null;try{$book=$Excel.Workbooks.Add();$book.Worksheets.Item(1).Range('A1').Value2='normal';$book.SaveAs($Path,51);$book.Close($false);$book=$null}finally{if($null -ne $book){try{$book.Close($false)}catch{}};Release-Com $book} }
function New-EncryptedFixture([object]$Excel,[string]$Path) { $book=$null;try{$book=$Excel.Workbooks.Add();$book.Worksheets.Item(1).Range('A1').Value2='encrypted';$book.SaveAs($Path,51,'r58-safe-open-password');$book.Close($false);$book=$null}finally{if($null -ne $book){try{$book.Close($false)}catch{}};Release-Com $book} }
function New-LegacyFixture([object]$Excel,[string]$Path) { $book=$null;try{$book=$Excel.Workbooks.Add();$book.Worksheets.Item(1).Range('A1').Value2='legacy';$book.SaveAs($Path,56);$book.Close($false);$book=$null}finally{if($null -ne $book){try{$book.Close($false)}catch{}};Release-Com $book} }
function Invoke-Probe([object]$Excel,[string]$Macro,[object[]]$Arguments){
    if($Arguments.Count -eq 3){$value=[string]$Excel.Run($Macro,$Arguments[0],$Arguments[1],$Arguments[2])}
    elseif($Arguments.Count -eq 4){$value=[string]$Excel.Run($Macro,$Arguments[0],$Arguments[1],$Arguments[2],$Arguments[3])}
    else{throw ('Safe-open probe argument count is unsupported: '+$Arguments.Count)}
    if($value -notmatch '^(PASS|REJECTED)\|'){throw ('Safe-open VBA probe failed: '+$value)}
    return $value
}

$Cases=New-Object 'Collections.Generic.List[object]';$excel=$null;$binding=$null;$books=$null;$copy=$null;$project=$null;$components=$null;$sourceHash=$null;$sourceHashAfter=$null;$copyPath=$null;$fixtureRoot=$null;$markerPath=$null;$userOwned=$null;$positiveControlBook=$null;$failure=$null;$failureScriptStackTrace=$null;$failureStage='initialize';$cleanup=$null;$Compile=[ordered]@{status='NOT_RUN';control_id=578;active_project=$null;dialog=$null;failure=$null};$priorSecurity=$null;$priorEvents=$null;$stateCaptured=$false;$priorProfilePresent=Test-Path Env:LHEXCEL_PROFILE_ROOT;$priorProfile=[Environment]::GetEnvironmentVariable('LHEXCEL_PROFILE_ROOT','Process');$isolatedProfileRoot=$null
try {
    $failureStage='prepare_evidence';Add-Type -AssemblyName System.IO.Compression;Add-Type -AssemblyName System.IO.Compression.FileSystem
    [void](New-Item -ItemType Directory -Path $EvidenceRoot);$fixtureRoot=Join-Path $EvidenceRoot 'f';[void](New-Item -ItemType Directory -Path $fixtureRoot);$isolatedProfileRoot=Join-Path $EvidenceRoot 'p';[void](New-Item -ItemType Directory -Path $isolatedProfileRoot);[Environment]::SetEnvironmentVariable('LHEXCEL_PROFILE_ROOT',$isolatedProfileRoot,'Process')
    $failureStage='copy_product';$sourceHash=(Get-FileHash -LiteralPath $ProductXlam -Algorithm SHA256).Hash.ToLowerInvariant();$copyPath=Join-Path $EvidenceRoot 'p.xlam';Copy-Item -LiteralPath $ProductXlam -Destination $copyPath -ErrorAction Stop
    $failureStage='start_owned_excel';$baseline=Get-ExcelProcessBaseline;$excel=New-Object -ComObject Excel.Application;$binding=Get-ExactExcelProcessOwnership $excel $baseline 'R58 safe-open Excel';if(-not $binding.owned){throw ('Excel ownership rejected: '+$binding.failure)}
    $failureStage='instrument_and_compile_product';$excel.Visible=$false;$excel.DisplayAlerts=$false;$priorSecurity=[int]$excel.AutomationSecurity;$priorEvents=[bool]$excel.EnableEvents;$stateCaptured=$true;$books=$excel.Workbooks;$copy=$books.Open($copyPath,$false,$false);if($copy.ReadOnly){throw 'Instrumented Product copy opened read-only'};$project=$copy.VBProject;$components=$project.VBComponents;Add-VbaModule $components (Join-Path $SourceRoot 'tests/vba/file/T_R58SafeOpen.bas') 'T_R58SafeOpen';$copy.Save();Release-Com $components;$components=$null;Release-Com $project;$project=$null;$copy.Close($false);Release-Com $copy;$copy=$null;$copy=$books.Open($copyPath,$false,$false);Assert-InstrumentedCopyModule $copy 'T_R58SafeOpen';$project=$copy.VBProject;$components=$project.VBComponents;Invoke-R58SafeOpenCompile $excel $binding $components $copyPath
    $macro="'"+$copy.Name.Replace("'","''")+"'!"
    $xlsx=Join-Path $fixtureRoot 'normal.xlsx';$xlsm=Join-Path $fixtureRoot 'marker.xlsm';$markerPath=Join-Path $fixtureRoot 'workbook-open.marker';$corrupt=Join-Path $fixtureRoot 'corrupt.xlsx';$dtd=Join-Path $fixtureRoot 'dtd.xlsx';$macroSheet=Join-Path $fixtureRoot 'macrosheet.xlsx';$contentType=Join-Path $fixtureRoot 'content-type.xlsx';$relation=Join-Path $fixtureRoot 'relation.xlsx';$encrypted=Join-Path $fixtureRoot 'encrypted.xlsx';$legacy=Join-Path $fixtureRoot 'legacy.xls'
    $failureStage='fixture_normal_xlsx';New-NormalXlsxFixture $excel $xlsx;$failureStage='fixture_ooxml_rejections';New-OoxmlFixture $dtd 'dtd';New-OoxmlFixture $macroSheet 'macrosheet';New-OoxmlFixture $contentType 'content-type';New-OoxmlFixture $relation 'relation';[IO.File]::WriteAllText($corrupt,'not-a-zip',(New-Object Text.UTF8Encoding($false)));$failureStage='fixture_marker_xlsm';New-XlsmMarkerFixture $excel $xlsm $markerPath;$failureStage='fixture_encrypted_xlsx';New-EncryptedFixture $excel $encrypted;$failureStage='fixture_legacy_xls';New-LegacyFixture $excel $legacy
    $failureStage='positive_control';$positiveBefore=(Get-FileHash -LiteralPath $xlsm -Algorithm SHA256).Hash.ToLowerInvariant();$excel.AutomationSecurity=1;$excel.EnableEvents=$true;$positiveFailure=$null
    try {$positiveControlBook=$books.Open($xlsm,$false,$true)} catch {$positiveFailure=$_.Exception.Message} finally {if($null -ne $positiveControlBook){try{$positiveControlBook.Close($false)}catch{};Release-Com $positiveControlBook;$positiveControlBook=$null}}
    $positiveAfter=(Get-FileHash -LiteralPath $xlsm -Algorithm SHA256).Hash.ToLowerInvariant();if($positiveBefore -ne $positiveAfter){throw 'Positive-control direct open changed marker fixture hash'}
    if(Test-Path -LiteralPath $markerPath){$Cases.Add([pscustomobject]@{name='marker_positive_control';status='PASS';security=1;events=$true;source_sha256_before=$positiveBefore;source_sha256_after=$positiveAfter});Remove-Item -LiteralPath $markerPath -Force}
    else{$positiveReason='Workbook_Open marker did not execute under direct isolated Excel open; policy may block macros';if(-not [string]::IsNullOrWhiteSpace($positiveFailure)){$positiveReason='Direct positive-control open failed: '+$positiveFailure};$Cases.Add([pscustomobject]@{name='marker_positive_control';status='NOT_EVALUATED';security=1;events=$true;source_sha256_before=$positiveBefore;source_sha256_after=$positiveAfter;reason=$positiveReason})}
    $openModes=@(@{name='security_low_events_enabled';security=1;events=$true},@{name='security_force_disable_events_disabled';security=3;events=$false})
    foreach($mode in $openModes){$excel.AutomationSecurity=[int]$mode.security;$excel.EnableEvents=[bool]$mode.events;foreach($input in @($xlsx,$xlsm)){$failureStage='accepted_'+$mode.name+'_'+[IO.Path]::GetFileName($input);if($input -eq $xlsm -and (Test-Path -LiteralPath $markerPath)){throw 'Unexpected marker exists before safe-open'};$before=(Get-FileHash -LiteralPath $input -Algorithm SHA256).Hash.ToLowerInvariant();$result=Invoke-Probe $excel ($macro+'NxR58SafeOpenProbeClosedSnapshot') @($input,[int]$mode.security,[bool]$mode.events);$after=(Get-FileHash -LiteralPath $input -Algorithm SHA256).Hash.ToLowerInvariant();if($before -ne $after){throw ('Safe-open changed source hash: '+$input)};if($input -eq $xlsm -and (Test-Path -LiteralPath $markerPath)){throw 'Workbook_Open marker executed during safe-open'};$Cases.Add([pscustomobject]@{name=('accepted_'+$mode.name+'_'+[IO.Path]::GetFileName($input));status='PASS';security=[int]$mode.security;events=[bool]$mode.events;probe=$result;source_sha256_before=$before;source_sha256_after=$after})}}
    foreach($input in @($macroSheet,$contentType,$relation,$corrupt,$dtd,$encrypted,$legacy)){ $failureStage='rejected_'+[IO.Path]::GetFileName($input);$result=Invoke-Probe $excel ($macro+'NxR58SafeOpenProbeRejectedInput') @($input,3,$false);$Cases.Add([pscustomobject]@{name='rejected_'+[IO.Path]::GetFileName($input);status='PASS';probe=$result}) }
    $failureStage='user_owned_open_untouched';$excel.AutomationSecurity=3;$excel.EnableEvents=$false;$userOwned=$books.Open($xlsx,$false,$false);$userOwned.Worksheets.Item(1).Range('A1').Value2='user-unsaved';$result=Invoke-Probe $excel ($macro+'NxR58SafeOpenProbeUserOwnedOpen') @($xlsx,'user-unsaved',3,$false);if($userOwned.Saved){throw 'User-owned fixture Saved state changed'};$Cases.Add([pscustomobject]@{name='user_owned_open_untouched';status='PASS';probe=$result});$userOwned.Close($false);Release-Com $userOwned;$userOwned=$null
    $excel.AutomationSecurity=$priorSecurity;$excel.EnableEvents=$priorEvents
} catch {$failure=$_.Exception.Message;$failureScriptStackTrace=$_.ScriptStackTrace} finally {
    if($null -ne $positiveControlBook){try{$positiveControlBook.Close($false)}catch{}};if($null -ne $userOwned){try{$userOwned.Close($false)}catch{}};if($null -ne $excel -and $stateCaptured){try{$excel.AutomationSecurity=[int]$priorSecurity;$excel.EnableEvents=[bool]$priorEvents}catch{}};foreach($item in @($components,$project,$copy,$books,$positiveControlBook,$userOwned)){Release-Com $item};if($null -ne $excel){try{$excel.Quit()}catch{};Release-Com $excel};[GC]::Collect();[GC]::WaitForPendingFinalizers();[GC]::Collect();[GC]::WaitForPendingFinalizers();if($null -ne $binding -and $null -ne $binding.process){$cleanup=Stop-ExactProcessAfterGrace $binding.process 'R58 safe-open Excel' 15000 -Detailed;try{$binding.process.Dispose()}catch{}}
    if($priorProfilePresent){[Environment]::SetEnvironmentVariable('LHEXCEL_PROFILE_ROOT',$priorProfile,'Process')}else{[Environment]::SetEnvironmentVariable('LHEXCEL_PROFILE_ROOT',$null,'Process')}
}
if($null -eq $failure){$failureStage='verify_source_hash'};$sourceHashAfter=if(Test-Path $ProductXlam){(Get-FileHash -LiteralPath $ProductXlam -Algorithm SHA256).Hash.ToLowerInvariant()}else{$null};if($null -ne $sourceHash -and $sourceHashAfter -ne $sourceHash){$failureStage='verify_source_hash';$failure='Supplied Product.xlam changed during safe-open suite'};if($null -eq $failure){$failureStage='complete'};$remainingCheck=Wait-FreshExcelProcessExit 2000;$remaining=@($remainingCheck.remaining_pids);$failedCases=@($Cases|Where-Object{$_.status -ne 'PASS'}).Count;$status=if($null -eq $failure -and $Compile.status -eq 'PASS' -and $Cases.Count -eq 13 -and $failedCases -eq 0 -and $remaining.Count -eq 0){'PASS'}else{'DIAGNOSTIC'};$receipt=[ordered]@{schema_version=1;suite='R58SafeOpen';status=$status;run_id=$RunId;source_product_sha256=$sourceHash;source_product_sha256_after=$sourceHashAfter;instrumented_copy=$copyPath;profile_root=$isolatedProfileRoot;compile=$Compile;cases=@($Cases.ToArray());failed_case_count=$failedCases;failure_stage=$failureStage;failure=$failure;failure_script_stacktrace=$failureScriptStackTrace;cleanup=$cleanup;remaining_excel=$remaining;completed_utc=[DateTime]::UtcNow.ToString('o')};Write-Json (Join-Path $EvidenceRoot 'R58SafeOpen.json') $receipt;if($status -eq 'PASS'){Write-Output 'PASS|R58SafeOpen|13/13';exit 0};Write-Output ('DIAGNOSTIC|R58SafeOpen|'+$Cases.Count+'/13');throw ('R58 safe-open failed; receipt='+(Join-Path $EvidenceRoot 'R58SafeOpen.json'))
